version: "3.7"
services:
  front:
    container_name: react-handson
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # ./を/frontにバインドマウント
      - type: bind
        source: ./
        target: /react-handson
    working_dir: /react-handson
    command: npm start
    # 標準入出力先のデバイス コンテナが正常終了するのを防ぐ コンテナを持続させる
    tty: true
    ports:
      # コンテナの3000ポートをホストマシンの3000ポートに割り当てる
      # ホスト側：コンテナ側
      - 3000:3000
